name: price-optimization
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.0
  - numpy=2.2.5
  - pandas=2.2.3
  - matplotlib=3.10.1
  - scikit-learn=1.6.1
  - streamlit=1.45.0
  - plotly=6.0.1
  - seaborn=0.13.2
  - watchdog=4.0.2
  - statsmodels=0.14.4  
  - jupyter=1.1.1
  - ipywidgets=7.7.2
  - openpyxl=3.1.5
  - nbformat=5.10.4  
  - pip=25.1.1  